name: nougat-gpu
channels:
  - pytorch
  - nvidia
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:

  - blas=1.0
  - brotli-python=1.0.9
  - ca-certificates=2025.2.25
  - certifi=2025.4.26
  - charset-normalizer=3.3.2
  - filelock=3.17.0
  - freeglut=3.4.0
  - freetype=2.13.3
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - idna=3.7
  - intel-openmp=2023.1.0
  - jinja2=3.1.6
  - jpeg=9e
  - lcms2=2.16
  - lerc=4.0.0
  - libdeflate=1.22
  - libjpeg-turbo=2.0.0
  - libpng=1.6.39
  - libtiff=4.7.0
  - libuv=1.48.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - networkx=3.2.1
  - numpy=2.0.1
  - numpy-base=2.0.1
  - openjpeg=2.5.2
  - openssl=3.0.16
  - pillow=11.1.0
  - pip=25.1
  - pysocks=1.7.1
  - python=3.9.21
  - pytorch=2.5.1
  - pytorch-cuda=11.8 # This is crucial. PyTorch will handle CUDA dependencies.
  - pytorch-mutex=1.0
  - pyyaml=6.0.2
  - requests=2.32.3
  - setuptools=78.1.1
  - sqlite=3.45.3
  - tbb=2021.8.0
  - typing_extensions=4.12.2
  - urllib3=2.3.0
  - wheel=0.45.1
  - xz=5.6.4
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.6

  - pip:
    - accelerate==1.7.0
    - acres==0.3.0
    - aiohappyeyeballs==2.6.1
    - aiohttp==3.11.18
    - aiosignal==1.3.2
    - albucore==0.0.24
    - albumentations==1.4.3
    - annotated-types==0.7.0
    - async-timeout==5.0.1
    - attrs==25.3.0
    - audioread==3.0.1
    - cffi==1.17.1
    - ci-info==0.3.0
    - click==8.1.8
    - colorama==0.4.6
    - configobj==5.0.9
    - configparser==7.2.0
    - contourpy==1.3.0
    - cycler==0.12.1
    - datasets==2.14.4
    - decorator==5.2.1
    - dill==0.3.7
    - et-xmlfile==2.0.0
    - etelemetry==0.3.1
    - eval-type-backport==0.2.2
    - fitz==0.0.1.dev2
    - fonttools==4.58.0
    - frozenlist==1.6.0
    - fsspec==2025.3.2
    - httplib2==0.22.0
    - huggingface-hub==0.31.4
    - imageio==2.37.0
    - importlib-resources==6.5.2
    - isodate==0.6.1
    - joblib==1.5.0
    - kiwisolver==1.4.7
    - lazy-loader==0.4
    - levenshtein==0.27.1
    - librosa==0.11.0
    - lightning==2.5.1.post0
    - lightning-utilities==0.14.3
    - llvmlite==0.43.0
    - looseversion==1.3.0
    - lxml==5.4.0
    - matplotlib==3.9.4
    - msgpack==1.1.0
    - multidict==6.4.4
    - multiprocess==0.70.15
    - munch==4.0.0
    - nibabel==5.3.2
    - nipype==1.10.0
    - nltk==3.9.1
    - nougat-ocr==0.1.17
    - numba==0.60.0
    - opencv-python==4.11.0.86
    - opencv-python-headless==4.11.0.86
    - openpyxl==3.1.5
    - orjson==3.10.18
    - packaging==24.2
    - pandas==2.2.3
    - pathlib==1.0.1
    - platformdirs==4.3.8
    - pooch==1.8.2
    - propcache==0.3.1
    - prov==2.0.1
    - psutil==7.0.0
    - puremagic==1.29
    - py-cpuinfo==9.0.0
    - pyarrow==20.0.0
    - pycparser==2.22
    - pydantic==1.10.22
    - pydantic-core==2.33.2
    - pydot==4.0.0
    - pymupdf==1.25.5
    - pyparsing==3.2.3
    - pypdf==5.5.0
    - pypdfium2==4.30.1
    - python-dateutil==2.9.0.post0
    - python-levenshtein==0.27.1
    - pytorch-lightning==2.5.1.post0
    - pytz==2025.2
    - pyxnat==1.6.3
    - rapidfuzz==3.13.0
    - rdflib==6.3.2
    - regex==2024.11.6
    - ruamel-yaml==0.18.10
    - ruamel-yaml-clib==0.2.12
    - safetensors==0.5.3
    - scikit-image==0.24.0
    - scikit-learn==1.6.1
    - scipy==1.13.1
    - sconf==0.2.5
    - seaborn==0.13.2
    - sentencepiece==0.2.0
    - simplejson==3.20.1
    - simsimd==6.2.1
    - six==1.17.0
    - sounddevice==0.5.2
    - soundfile==0.13.1
    - soxr==0.5.0.post1
    - stringzilla==3.12.5
    - sympy==1.13.1
    - threadpoolctl==3.6.0
    - tifffile==2024.8.30
    - timm==0.5.4
    - tokenizers==0.13.3
    - torchaudio==2.5.1
    - torchmetrics==1.7.1
    - torchvision==0.20.1
    - tqdm==4.67.1
    - traits==7.0.2
    - transformers==4.31.0
    - typing-inspection==0.4.0
    - tzdata==2025.2
    - ultralytics==8.3.141
    - ultralytics-thop==2.0.14
    - xxhash==3.5.0
    - yarl==1.20.0
    - zipp==3.21.0